### ISSUE TITLE
RST(4) marker found where not allowed

### ISSUE THREAD

**Issue by bestouff** [kaksmet/jpeg-decoder#52]
Hi,

while decoding the attached picture (warning: atrocious child torture inside😄), I got this panic:
```
RUST_BACKTRACE=1 cargo run --example decode /home/xav/IMG_20160204_195730.jpg
     Running `target/debug/examples/decode /home/xav/IMG_20160204_195730.jpg`
thread 'main' panicked at 'decode failed: Format("RST(4) marker found where not allowed")', src/libcore/result.rs:788
stack backtrace:
   1:     0x557f362055ef - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x557f36208a9b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x557f3620871f - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x557f361fe82e - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x557f36208ce1 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x557f361ff0fa - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x557f36208c7e - rust_begin_unwind
   8:     0x557f3623b04f - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x557f3614fe4d - core::result::unwrap_failed::h946c0fb8477dc56c
                        at /build/rustc-5moGoL/rustc-1.11.0+dfsg1/src/libcore/macros.rs:29
  10:     0x557f3614fc39 - _<core..result..Result<T, E>>::expect::h65575c6cf47ed0a8
                        at /build/rustc-5moGoL/rustc-1.11.0+dfsg1/src/libcore/result.rs:750
  11:     0x557f36149bc4 - decode::main::h25b6bb75384c0f31
                        at /home/xav/rust/jpeg-decoder/examples/decode.rs:57
  12:     0x557f36208328 - std::panicking::try::call::hca715a47aa047c49
  13:     0x557f3621018b - __rust_try
  14:     0x557f3621012e - __rust_maybe_catch_panic
  15:     0x557f36207dce - std::rt::lang_start::h162055cb2e4b9fe7
  16:     0x557f361973b9 - main
  17:     0x7fc5433902b0 - __libc_start_main
  18:     0x557f36148ca9 - _start
  19:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/examples/decode /home/xav/IMG_20160204_195730.jpg` (exit code: 101)
```
[img_20160204_195730](https://cloud.githubusercontent.com/assets/1163188/19079329/972d2b72-8a53-11e6-8fe5-068ac2e1d8c4.jpg)

**Comment by kaksmet** [comment]
Thanks for reporting this.

I think I know what the problem is and will be working on a fix tonight.

**Comment by bestouff** [comment]
Perfect. Thanks for your reactivity !

**Comment by kaksmet** [comment]
`0.1.7` has now been published on crates.io, which contains the fix for this issue.
